---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: cloud-credentials
  namespace: open-cluster-management-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: cloud-credentials
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.oadp.key }}
