apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: multiclusterhub-operator-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .content }}` }}"
  data:
  - secretKey: content
    remoteRef:
      key: {{ .Values.pullSecret.key }}